export const TRANSCRIBE_PROGRESS_INITIAL_PERCENT = -1
export const TRANSCRIBE_PROGRESS_MIN_PERCENT = 0
export const TRANSCRIBE_PROGRESS_MAX_PERCENT = 100
export const TRANSCRIBE_PROGRESS_JOB_CREATED_PERCENT = 2

export const TRANSCRIBE_UPLOAD_PROGRESS_PERCENT = 60
export const TRANSCRIBE_STREAMING_PROGRESS_START_PERCENT = 72
export const TRANSCRIBE_STREAMING_PROGRESS_MAX_PERCENT = 98
export const TRANSCRIBE_TOKEN_PROGRESS_STEP_DIVISOR = 120
export const TRANSCRIBE_TOKEN_PROGRESS_MIN_STEP = 1

