export const HTTP_STATUS_OK = 200
export const HTTP_STATUS_ACCEPTED = 202
export const HTTP_STATUS_BAD_REQUEST = 400
export const HTTP_STATUS_UNAUTHORIZED = 401
export const HTTP_STATUS_CONFLICT = 409
export const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
export const HTTP_STATUS_SERVICE_UNAVAILABLE = 503
export const HTTP_STATUS_TOO_MANY_REQUESTS = 429
