FROM node:24-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

RUN yarn install --immutable

COPY . .

RUN yarn workspace @julia/server build

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=4321
ENV JULIA_AGENT_GRPC_PORT=50051

EXPOSE 4321
EXPOSE 50051

CMD ["node", "./apps/server/dist/server/entry.mjs"]
