import {
  PASSPORT_AGENT_DEV_MODE_ENV_KEY,
  PASSPORT_GRPC_PORT_DEFAULT,
  PASSPORT_GRPC_PORT_ENV_KEY,
  PASSPORT_GRPC_PORT_MAX,
  PASSPORT_GRPC_PORT_MIN,
  PASSPORT_HEARTBEAT_TIMEOUT_DEFAULT_MS,
  PASSPORT_HEARTBEAT_TIMEOUT_ENV_KEY,
  PASSPORT_HEARTBEAT_TIMEOUT_MAX_MS,
  PASSPORT_HEARTBEAT_TIMEOUT_MIN_MS,
  PASSPORT_PROTOCOL_PROTO_PATH_ENV_KEY,
  TRANSCRIBE_AGENT_MOCK_MODE_ENV_KEY,
} from '@shared/config/passport-runtime'
import {
  SHELL_STATUS_POLL_INTERVAL_DEFAULT_MS as SHELL_STATUS_POLL_INTERVAL_DEFAULT,
  SHELL_STATUS_POLL_INTERVAL_ENV_KEY as SHELL_STATUS_POLL_INTERVAL_ENV,
  SHELL_STATUS_POLL_INTERVAL_MAX_MS as SHELL_STATUS_POLL_INTERVAL_MAX,
  SHELL_STATUS_POLL_INTERVAL_MIN_MS as SHELL_STATUS_POLL_INTERVAL_MIN,
} from '@shared/config/shell-status-polling'

export const ENV_KEYS = {
  shellStatusPollIntervalMs: SHELL_STATUS_POLL_INTERVAL_ENV,
  passportHeartbeatTimeoutMs: PASSPORT_HEARTBEAT_TIMEOUT_ENV_KEY,
  passportGrpcPort: PASSPORT_GRPC_PORT_ENV_KEY,
  passportAgentDevModeEnabled: PASSPORT_AGENT_DEV_MODE_ENV_KEY,
  passportProtocolProtoPath: PASSPORT_PROTOCOL_PROTO_PATH_ENV_KEY,
  transcribeAgentMockModeEnabled: TRANSCRIBE_AGENT_MOCK_MODE_ENV_KEY,
  geminiModel: 'GEMINI_MODEL',
} as const

export const ENV_DEFAULTS = {
  shellStatusPollIntervalMs: SHELL_STATUS_POLL_INTERVAL_DEFAULT,
  passportHeartbeatTimeoutMs: PASSPORT_HEARTBEAT_TIMEOUT_DEFAULT_MS,
  passportGrpcPort: PASSPORT_GRPC_PORT_DEFAULT,
} as const

export const ENV_LIMITS = {
  shellStatusPollIntervalMs: {
    min: SHELL_STATUS_POLL_INTERVAL_MIN,
    max: SHELL_STATUS_POLL_INTERVAL_MAX,
  },
  passportHeartbeatTimeoutMs: {
    min: PASSPORT_HEARTBEAT_TIMEOUT_MIN_MS,
    max: PASSPORT_HEARTBEAT_TIMEOUT_MAX_MS,
  },
  passportGrpcPort: {
    min: PASSPORT_GRPC_PORT_MIN,
    max: PASSPORT_GRPC_PORT_MAX,
  },
} as const
