export const PASSPORT_HEARTBEAT_TIMEOUT_ENV_KEY = 'JULIA_AGENT_HEARTBEAT_TIMEOUT_MS'
export const PASSPORT_HEARTBEAT_TIMEOUT_DEFAULT_MS = 60_000
export const PASSPORT_HEARTBEAT_TIMEOUT_MIN_MS = 5_000
export const PASSPORT_HEARTBEAT_TIMEOUT_MAX_MS = 600_000

export const PASSPORT_GRPC_PORT_ENV_KEY = 'JULIA_AGENT_GRPC_PORT'
export const PASSPORT_GRPC_PORT_DEFAULT = 50_051
export const PASSPORT_GRPC_PORT_MIN = 1
export const PASSPORT_GRPC_PORT_MAX = 65_535

export const PASSPORT_AGENT_DEV_MODE_ENV_KEY = 'JULIAAPP_AGENT_ENABLE_DEV'
export const PASSPORT_PROTOCOL_PROTO_PATH_ENV_KEY = 'JULIAAPP_PROTOCOL_PROTO_PATH'
export const TRANSCRIBE_AGENT_MOCK_MODE_ENV_KEY = 'JULIAAPP_AGENT_MOCK_MODE'

export const PUBLIC_AGENT_RELEASES_BASE_URL_ENV_KEY = 'PUBLIC_AGENT_RELEASES_BASE_URL'
export const PUBLIC_AGENT_RELEASES_BASE_URL_DEFAULT =
  'https://github.com/kubefox-bot/julia-shell/releases/latest/download'
