import { TERMINAL_AGENT_WIDGET_ID, TRANSCRIBE_WIDGET_ID } from '@/widgets';

export const PASSPORT_ACCESS_COOKIE_NAME = 'julia_access_token';
export const PASSPORT_ANONYMOUS_AGENT_ID = 'public-anonymous';
export const PASSPORT_WIDGET_ID_TRANSCRIBE = TRANSCRIBE_WIDGET_ID;
export const PASSPORT_WIDGET_ID_TERMINAL_AGENT = TERMINAL_AGENT_WIDGET_ID;

const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;
const DAYS_PER_WEEK = 7;

const ACCESS_TTL_HOURS = 12;
const ENROLLMENT_TTL_DEFAULT_MINUTES = 60;
const ENROLLMENT_TOKEN_BYTES = 32;
const REFRESH_TOKEN_BYTES = 48;

export const PASSPORT_ACCESS_TTL_SECONDS = SECONDS_PER_MINUTE * MINUTES_PER_HOUR * ACCESS_TTL_HOURS;
export const PASSPORT_REFRESH_TTL_DAYS = 30;

export const PASSPORT_ENROLLMENT_DEFAULT_TTL_MINUTES = ENROLLMENT_TTL_DEFAULT_MINUTES;
export const PASSPORT_ENROLLMENT_MIN_TTL_MINUTES = 1;
export const PASSPORT_ENROLLMENT_MAX_TTL_MINUTES = ENROLLMENT_TTL_DEFAULT_MINUTES * HOURS_PER_DAY * DAYS_PER_WEEK;

export const PASSPORT_ENROLLMENT_DEFAULT_USES = 1;
export const PASSPORT_ENROLLMENT_MIN_USES = 1;
export const PASSPORT_ENROLLMENT_MAX_USES = 10;
export const PASSPORT_ENROLLMENT_TOKEN_BYTES = ENROLLMENT_TOKEN_BYTES;
export const PASSPORT_REFRESH_TOKEN_BYTES = REFRESH_TOKEN_BYTES;

export const PASSPORT_AGENT_STATUS_ONLINE = 'online';
export const PASSPORT_AGENT_STATUS_DISCONNECTED = 'disconnected';
export const PASSPORT_AGENT_STATUS_ENROLLMENT_PENDING = 'enrollment_pending';

export const PASSPORT_TOKEN_TYPE_REFRESH = 'refresh';
